spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/weiketang
      username: userAdmin

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


server:
  servlet:
    encoding:
      charset: utf-8